### ISSUE TITLE
Polygon factory crypto pools doesn't return on api

### ISSUE THREAD

**Issue by guveniscan** [curvefi/curve-api#302]
In the API response factory crypto-v2 pools are not available, for example these 2 pools are not there:

https://curve.fi/#/polygon/pools/factory-crypto-1
https://curve.fi/#/polygon/pools/factory-crypto-13

I've tried both endpoints:
https://api.curve.fi/api/getPools/polygon/crypto
https://api.curve.fi/api/getPools/polygon/factory

**Comment by philippe-git** [comment]
Seeing how late I reply, I doubt you still need help, but in case you do, both pools can be found in this endpoint that returns *all* Polygon pools: https://api.curve.fi/api/getPools/all/polygon
