### ISSUE TITLE
Tricrypto Optimized pools (Vyper 0.3.9) not found in getPools API

### ISSUE THREAD

**Issue by Gaon3** [curvefi/curve-api#305]
https://curve.fi/#/ethereum/pools/factory-tricrypto-0
https://curve.fi/#/ethereum/pools/factory-tricrypto-1

The new pools are not included in any of the sections of the getPools API call.

**Comment by philippe-git** [comment]
Seeing how late I reply, I doubt you still need help, but in case you do, both pools can be found in this endpoint that returns all Ethereum pools: https://api.curve.fi/api/getPools/all/ethereum
