### ISSUE TITLE
Pool fee parameters in pools apis

### ISSUE THREAD

**Issue by pata-eth** [curvefi/curve-api#316]
As an aggregator I could more conveniently and more precisely quote swaps if I had access to the fees of each pool in the api. That way I could adjust the output of get_dy/get_dy_underlying by the amount of the fees and quote curve swaps more precisely. Please let me know if you have other suggestions as well. Many thanks

**Comment by bout3fiddy** [comment]
Does this work for you: https://github.com/curvefi/curve-zaps

**Comment by pata-eth** [comment]
Thanks @bout3fiddy. That may just be what I need. I'll be out next week but I'll check it out when I'm back. I'll re-open if there's the need. Thanks again ser
