### ISSUE TITLE
stable-ng pools support

### ISSUE THREAD

**Issue by poolpitako** [curvefi/curve-api#319]
Hello!

I noticed that `CurveStableSwapNG` pools started popping up in Ethereum. EG: https://dao.curve.fi/vote/ownership/483
Can you add support to them in the API? Not sure if these type of pools will be listed under a different endpoint 🤷 

Thanks ❤️

**Comment by philippe-git** [comment]
Hehe, they're already here! https://api.curve.fi/api/getPools/ethereum/factory-stable-ng 🫡
