### ISSUE TITLE
potential mislabeling of pools

### ISSUE THREAD

**Issue by pata-eth** [curvefi/curve-api#321]
The pools below show up under the `main` registry id, when they should be under the `factory` registry id.

0xEcd5e75AFb02eFa118AF914515D6521aaBd189F1
0x4807862AA8b2bF68830e4C8dc86D0e9A998e085a

https://api.curve.fi/api/getPools/ethereum/main

**Comment by philippe-git** [comment]
This is another legacy behavior in the same vein as the one described here: https://github.com/curvefi/curve-api/issues/320
These factory pools weren't created from the current factory registry (there once was an older, short-lived v1 factory registry that has been superseded by the current one). Pools from that old registry were added to the main registry, and that old v1 factory registry isn't really used anywhere anymore.

The API now has an endpoint that returns all pools on Ethereum by the way, you don't need to go registry by registry anymore: https://api.curve.fi/api/getPools/all/ethereum
