### ISSUE TITLE
factory stable ng registry needs `zapAddress` in getPools endpoint

### ISSUE THREAD

**Issue by pata-eth** [curvefi/curve-api#322]
for consistency across registries, `zapAddress` - 0xA79828DF1850E8a3A3064576f380D90aECDD3359 - should be added to USD metapools in the factory stable ng registry.

**Comment by philippe-git** [comment]
The `zapAddress` prop was added to stable-ng meta pools, however do note that the address is different (see https://api.curve.fi/api/getPools/ethereum/factory-stable-ng)
