### ISSUE TITLE
Incorrect pool type classification in polygon

### ISSUE THREAD

**Issue by bout3fiddy** [curvefi/curve-api#333]
From Kyberswap folks:

```
It seems that the offchain API is wrongly classifying this pool as a Meta pool, while it's just a Plain pool: https://curve.fi/#/polygon/pools/factory-v2-45/swap

So on the UI it allows swapping from AMIS to USDC/USDT but will get error when trying to calculate exchange rate (because it's just a Plain pool with 2 coins AMIS and am3CRV)

Could you please check that pool? (there are many other pools on other chains that get wrongly classified, it seems that they have 1 thing in common: one of their coins is the LP token of another Curve pool)
```

Upon checking this pool, it does look like a metapool:

![Image](https://github.com/curvefi/curve-api/assets/11488427/a04d0141-5c74-49f0-be1f-64f1736f4d51)

but the pool contract is a plain pool: 

![Image](https://github.com/curvefi/curve-api/assets/11488427/a2e66235-8435-46cd-8530-7ab07e6c31f5)

We need to classify pools based on the contract type. So in this case, we'd want to classify this pool as a plain pool. To check if a pool is a metapool or not, one can look for an `exchange_underlying` method perhaps. for NG, this should be simpler because it's metapools have a `base_pool` public getter.

Suggestion: maybe we can add a field whether the token is an LP token or not? so it would be useful for integrators? Then they'd know which pool that token belongs to, if it was a plain pool (or even a crypto pool) with an LP token in it.

**Comment by philippe-git** [comment]
Ah right, currently the API infers if a pool is a base pool by checking if there's another pool's lp token being used as a coin inside this pool. This is a false positive for sure, I'll update the metapool detection method to what you suggested which is much better

On the suggested field, the API already has `isBasePoolLpToken` on the coin object and `basePoolAddress` as well on the pool object:

<img width="584" alt="image" src="https://github.com/curvefi/curve-api/assets/2307365/66e7d8b4-352c-4fe9-9ce3-87adc3f1a360">

**Comment by bout3fiddy** [comment]
I would say instead of updating the existing method of detection with my proposed one, I'd _add_ it instead. Because some cryptoswap pools have `exchange_underlying` as well in them (if they have ETH).

**Comment by philippe-git** [comment]
Perfect, using pool implementations on top of the existing logic allowed to catch false positives, there were about 20 on polygon (including the pool mentioned in this issue), 5 on arbitrum, 7 on gnosis. Great catch!
