### ISSUE TITLE
polygon api returns wrong gauge address

### ISSUE THREAD

**Issue by bout3fiddy** [curvefi/curve-api#334]
Pool for [crvusd <> CRV](https://curve.fi/#/polygon/pools/factory-twocrypto-0/deposit) from api shows the following:

![Image](https://github.com/curvefi/curve-api/assets/11488427/47b5c38f-b3ef-47bf-a068-61a698c48708)

It shows the pool for [BNT <> BAL](https://polygonscan.com/address/0x16a3a047fc1d388d5846a73acdb475b11228c299#code)

It should show [0x0BC03BC0bcc5A9498F06B041A54eE54DEaaEe2dE](https://polygonscan.com/address/0x0BC03BC0bcc5A9498F06B041A54eE54DEaaEe2dE#readContract#F14):

![Image](https://github.com/curvefi/curve-api/assets/11488427/886c59d4-e748-49a6-b73c-830e260b33e9)

**Comment by philippe-git** [comment]
woopsie, that area of the code forgets to check for the chain id, so it matches on the swap address on any chain, and evidently these are not unique across all chains
