### ISSUE TITLE
Add new AddressProvider to the api

### ISSUE THREAD

**Issue by bout3fiddy** [curvefi/curve-api#340]
Contract deployed at: 0x5ffe7FB82894076ECB99A30D6A32e969e6e35E98 on the following networks:
Ethereum, Arbitrum, Optimism, Base, Bsc, Polygon, Fantom, Gnosis, Aurora, Celo, Mantle, Linea, Polygon zkEVM, Scroll, Fraxtal, Avalanche, Kava

**Comment by philippe-git** [comment]
Old address provider: 0x0000000022d53366457f9d5e68ec105046fc4383
