### ISSUE TITLE
gnosis sDAI base apr is zero

### ISSUE THREAD

**Issue by bout3fiddy** [curvefi/curve-api#347]
![Image](https://github.com/curvefi/curve-api/assets/11488427/0a8fe4e2-0d19-4200-b22e-4a0aaaeb93dd)

https://staging.curve.fi/#/xdai/pools/factory-stable-ng-3/deposit

whereas it is actually nonzero. turns out the shares grow once every three days ...

**Comment by philippe-git** [comment]
Fixed in 4e6ff9524fb5cb1573a81cd75174e347c950e401
