### ISSUE TITLE
Error in Gauge for gaugeCrvApy values sometimes

### ISSUE THREAD

**Issue by saint-rat** [curvefi/curve-api#359]
Currently these 2 pools have no gauge CRV rewards but are showing CRV rewards (data from getAllGauges method)
```
"fantom-s3CRV_e+s2CRV_ar+s3CRV_o+sav3CRV_av+sam3CRV_p+sb3pool_b+s4pool_ba+sx3CRV_g (0x3f83…De62)": {
      "isPool": true,
      "name": "fantom-s3CRV_e+s2CRV_ar+s3CRV_o+sav3CRV_av+sam3CRV_p+sb3pool_b+s4pool_ba+sx3CRV_g (0x3f83…De62)",
      "shortName": "ftm-CrossCurve Stable (0x3f83…)",
      "gauge": "0x9c3d261079fdb2a3511cf7cb6679d05029c109a8",
      "rootGauge": "0xa971354db30df69b35cf99b434875a32aea0718a",
      "side_chain": true,
      "gauge_data": {
        "inflation_rate": 46489740675387736,
        "working_supply": "956502661726593331858505"
      },
      "gauge_controller": {
        "gauge_relative_weight": "11566326649944245",
        "gauge_future_relative_weight": "11567846078547582",
        "get_gauge_weight": "9055782216816621043968000",
        "inflation_rate": 46489740675387736
      },
      "hasNoCrv": false,
      "is_killed": false,
      "lpTokenPrice": 1.0054206635709704,
      "gaugeCrvApy": [
        66.65149486975498,
        166.62873717438745
      ],
      "gaugeStatus": {
        "areCrvRewardsStuckInBridge": false,
        "rewardsNeedNudging": false
      },
```
```
"fantom-sWETH_e+sWETH_ar+sWETH_o+sWETH_ba+sWETH_m+sWETH_bl+sWETH_l+sWETH_t (0x3C2f…F18d)": {
      "isPool": true,
      "name": "fantom-sWETH_e+sWETH_ar+sWETH_o+sWETH_ba+sWETH_m+sWETH_bl+sWETH_l+sWETH_t (0x3C2f…F18d)",
      "shortName": "ftm-CrossCurve ETH (0x3C2f…)",
      "gauge": "0x358bc5b9a93eed859abc692684b746694fb9c509",
      "rootGauge": "0x170100aed2a922a570e5d105c29cc7158f3de359",
      "side_chain": true,
      "gauge_data": {
        "inflation_rate": 4920222235298684,
        "working_supply": "347251135481269431087"
      },
      "gauge_controller": {
        "gauge_relative_weight": "1159610903792711",
        "gauge_future_relative_weight": "1159438876628905",
        "get_gauge_weight": "907656091649879743584000",
        "inflation_rate": 4920222235298684
      },
      "hasNoCrv": false,
      "is_killed": false,
      "lpTokenPrice": 3863.5979169638003,
      "gaugeCrvApy": [
        5.056335488873737,
        12.640838722184341
      ],
```

Is not only an issue on fantom, myself and Mim saw this yesterday in relation to the DOLA+scrvUSD pool on Ethereum:
My message:

```
hmmm anyone know why on the curve-js API the /getPools/all/{blockchainId} method today can return different values compared to the /getPools/{blockchainId}/{registryId} method for the same pools in both lists?

E.g.       for DOLA+scrvUSD pool the /getPools/{blockchainId}/{registryId} has gauge rewards at 32.17%-80.43% CRV with $6M TVL
              for DOLA+scrvUSD pool the  /getPools/all/{blockchainId} has gauge rewards at 52.88%-132.07% CRV with $3M TVL

Realised I'm using the /getPools/all/{blockchainId} to scrape data for yield stats and it's very different today to what the frontend shows, should I assume only the API methods the frontend uses are correct and all others may not be?
```

Mim also saw the same issue for the same pool, but this time the getAllGauges, getPools/ethereum/factory-stable-ng and frontend were all showing different values:

**getAllGauges**
![image](https://github.com/user-attachments/assets/ade1bffe-a9ce-40e4-a2ae-513c914ad981)

**getPools/ethereum/factory-stable-ng**
![image](https://github.com/user-attachments/assets/e28e83a4-623b-4ec7-a22f-5d071afca81d)

**frontend**
![image](https://github.com/user-attachments/assets/edf3af95-3a30-4685-beb9-7a9eb0bc7b5d)

**Comment by saint-rat** [comment]
Hmm so realized that this isn't actually an error for the CrossCurve pools on Fantom, rewards are currently streaming, but the frontend is not currently showing them.

https://ftmscan.com/address/0x004a476b5b76738e34c86c7144554b9d34402f13

**Comment by philippe-git** [comment]
Hey, replied yesterday in the chat:

- No API issue for crosscurve fantom pools like you mentioned
- Differences you see can be explained by each endpoint being behind a different cache layer (+ using stale-while-revalidate so endpoints queried infrequently will have outdated data served first until revalidated). At the moment `getAllGauges` returns `[31.5955120163172, 78.988780040793]`, `getPools` same, `getPools/all` `[32.60267918216281,81.50669795540702]`, which are all within normal bounds given current CRV market volatility and different caching durations. These endpoints all use the same data source so different caching layers is the sole explanation for different numbers
